name: Deploy on Push
on:
  push:
    branches:
      - main
jobs:
  build:
    
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install ts-node-dev
        run: npm install -g ts-node-dev

      - name: echo variable
        run: echo ${{secrets.DB_URL}}

      - name: Build TypeScript
        run: npm run build 

      - name: Run your application
        run: npm run dev
        env: 
          DB_URL: ${{secrets.DB_URL}}

      - name: Use .env environment variables
        run: |
          echo DB_URL=${{secrets.DB_URL}} >> .env

      - name: Verificar conteúdo do .env
        run: cat .env

     
      
    
